### ISSUE TITLE
[e.g]add url of my blog to friends page of your blog 

### ISSUE THREAD

**Issue by ghost** [Mryan2005/mryan2005.github.io#5]
what's your blog name?
Mryan's blog
what's your blog url?
https://mryan2005.github.io
what is describe of your blog?
none

**Comment by Mryan2005** [comment]
so

**Comment by Mryan2005** [comment]
ok

**Comment by Mryan2005** [comment]
wait for write

**Comment by Mryan2005** [comment]
I have been add The url to footer of my blog
